### ISSUE TITLE
[Design]: Create a Responsive Navbar

### ISSUE THREAD

**Issue by Saumya40-codes** [Programming-Club-Ahmedabad-University/WOC-2024#1]
**Proposed Feature**
Implement a responsive navbar with links to Home, Events, Join Us, and Contact Us. The navbar should highlight the active section during scrolling.

**Additional Context**
- Please refer to [figma designs](https://www.figma.com/design/kHauIvxVeOb8diy8jO6jJd/Website?node-id=0-1&t=VaLTx4vGpSXga6dU-1)
- Might not be needed here, but if necessary you can use any of the [chakra-ui](https://www.chakra-ui.com/) components.

## Relevant Images/ScreenShots

![image](https://github.com/user-attachments/assets/ff7baec4-c5c6-44f8-ae39-4abc15c720cf)

**Comment by jeyasimma** [comment]
can I create a responsive navbar . Could you assign it to me?

**Comment by Saumya40-codes** [comment]
> can I create a responsive navbar . Could you assign it to me?

Thanks!

But this project is open to contribute only for the registered Ahmedabad University Pclub WOC participants

**Comment by KushalXCoder** [comment]
Can I work on it?

**Comment by Saumya40-codes** [comment]
Sure. You can start with it!

**Comment by KushalXCoder** [comment]
Can I add, on hover underline animation to the navbar links and also, for highlighting which section you are in ?

**Comment by Saumya40-codes** [comment]
> Can I add, on hover underline animation to the navbar links and also, for highlighting which section you are in ?

Yes, we can go with underline animation.
