### ISSUE TITLE
[CI]: Implement Github Workflow to check for potential lint errors

### ISSUE THREAD

**Issue by Saumya40-codes** [Programming-Club-Ahmedabad-University/WOC-2024#10]
## Description
**(Please ask to maintainer to assign this issue to you before working on it)**
To maintain code quality and ensure consistency across the codebase, it is important to set up a GitHub Actions workflow that runs linting checks on every pull request. This automated linting check will catch style violations, potential bugs, and other code quality issues before they are merged into the main branch.

For instance, eslint checks ensures that there are no unused imports in the file (meaning if we have useState import and haven't used, eslint will  throw an error/warning)

You can check out `eslint.config.js` file for more info about this. 

## Approach
1. **Create GitHub Actions Workflow**:
   - Set up a new GitHub Actions workflow in the `.github/workflows` directory that runs linting on every pull request and push to the `main` branch.
   
2. **Run Lint Command**:
   - The workflow should use the existing `npm run lint` command to execute ESLint, as defined in the `package.json` file.
   - Ensure the workflow installs the necessary dependencies before running the linting process (e.g., running `npm install`).
   
3. **Fail Workflow on Lint Issues**:
   - The workflow should fail if there are any linting issues, providing feedback on which files or lines need attention.

## Additional Context
- For more info about eslint you can check [this](https://eslint.org/docs/latest/use/core-concepts/)
- More about [github actions](https://docs.github.com/en/actions/about-github-actions/understanding-github-actions)
- Feel free to discuss here if you have any doubt.

**Comment by mini0192** [comment]
Can i make it?

**Comment by Saumya40-codes** [comment]
> Can i make it?

@mini0192 Thanks for the interest but contribution to this repository is limited to an inter-college event registered folks

**Comment by mini0192** [comment]
> > Can i make it?
> 
> @mini0192 Thanks for the interest but contribution to this repository is limited to an inter-college event registered folks

Okay thanks for reply!

**Comment by vrunda2005** [comment]
Can I work on this issue?

**Comment by AvishaiDotan** [comment]
@vrunda2005 Please update on this one
