### ISSUE TITLE
Update the Favicon(Tab Image) and Tab Title

### ISSUE THREAD

**Issue by Saumya40-codes** [Programming-Club-Ahmedabad-University/WOC-2024#14]
Currently the favicon icon and tab title are default Vite+React based templates.

1. We need to change icon to that Programming club logo
2. change text from `Vite+React` to `Pclub Ahmedabad University`

Relevant screenshot/image
![image](https://github.com/user-attachments/assets/b8f7753b-f242-48c1-854f-b881561ea02b)

### Approach:
1. Add pclub-logo image to public folder (You can see there already exists a vite.svg which is currently being used)
    - You can get logo in `png` or `jpeg` format directly by searching `ahmedabad university pclub` on google or any other medium
2. Headover to `index.html` file and update the name from `Vite+React` to `Pclub Ahmedabad University`
3. update this following line in `index.html` to change the image format/path

    ```
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
   ```

   for example, if image is in png format then

   ```   
   <link rel="icon" type="image/png" href="/pclub-logo.png" />
   ```

**Comment by KushalXCoder** [comment]
Can I work on it ?
