### ISSUE TITLE
[Component] Design an email subscription (join us component)    Hero Section (2/n)

### ISSUE THREAD

**Issue by Saumya40-codes** [Programming-Club-Ahmedabad-University/WOC-2024#15]
**Note: This issue is just about designing the component and not for email subscription logic (for now)**

### Description

Build the Join Us section, which includes:
- A text input field for the email address.
- A JOIN US button.

Approach:
- Create a JoinUs component
- Implement the input box and button.
- Add hover and focus effects to the JOIN US button.

## Additional Context

- Please refer to [**Figma Designs only**](https://www.figma.com/design/kHauIvxVeOb8diy8jO6jJd/Website?node-id=0-1&t=VaLTx4vGpSXga6dU-1) for this.
- You can use **lucide-react** for getting the preferred icons(if any): [https://lucide.dev/icons/]()

### Relevant Screenshot/Images
![image](https://github.com/user-attachments/assets/53b3604f-9893-44de-9898-52473d703d84)

**Comment by Bansi-Mahkana** [comment]
I would like to work on this issue. Could you please assign it to me?
I also wanted to confirm, is it okay if i implement this using HTML and CSS?

**Comment by Saumya40-codes** [comment]
> I would like to work on this issue. Could you please assign it to me? I also wanted to confirm, is it okay if i implement this using HTML and CSS?

Thanks for the interest @Bansi-Mahkana in working on this.

You can check out `/src/components/ExampleComponent` folder and you can wrap your html implementation in such react component and use the module.css for the css, for the scope of this issue there isnt much react that should be needed that is different than html 


For instance, if you would've had an html file like this

```
<div class='emailbox'>
      <input type='text' requires class='input' />
       <button type='submit' class='btn'>Submit</button>
</div>
```

Then its corresponding jsx code will be just

```
import React from 'react'
import styles from './ExampleComponentCss.module.css'

const EmailBoxComponent = () => {
  return (
    <div className={styles.emailbox}>
         <input type='text' requires className={styles.input} />
         <button type='submit' className={syles.btn}>Submit</button>
    </div>
  )
}

export default EmailBoxComponent 
```


In React, the structure is written using JSX, which ultimately gets compiled to HTML and CSS. So, writing raw HTML/CSS directly isn’t enough as the React expects components instead.

**Comment by Saumya40-codes** [comment]
You can still learn along the way while working on this!

**Comment by Saumya40-codes** [comment]
> I would like to work on this issue. Could you please assign it to me? I also wanted to confirm, is it okay if i implement this using HTML and CSS?

Should I assign it to you? 

You are free to open PR with the changes

**Comment by Bansi-Mahkana** [comment]
Thank you for clarifying! I understand that I need to use JSX and React components. I’m excited to learn and work on this issue. Yes, please assign it to me

**Comment by Saumya40-codes** [comment]
> Thank you for clarifying! I understand that I need to use JSX and React components. I’m excited to learn and work on this issue. Yes, please assign it to me

👍 You can start with it.

**Comment by Bansi-Mahkana** [comment]
> > Thank you for clarifying! I understand that I need to use JSX and React components. I’m excited to learn and work on this issue. Yes, please assign it to me
> 
> 👍 You can start with it.

Thank you! I'll get started on this issue.
