### ISSUE TITLE
[Component] Create a reusable InformationBox Component            (Hero Section 4/n)

### ISSUE THREAD

**Issue by Saumya40-codes** [Programming-Club-Ahmedabad-University/WOC-2024#17]
### Description

Create a reusable component of InformationBox

This component will accept following arguments/props
- Title
- Icon/Image
- InformationText

The component might be structured like this:
```
import React from 'react'

const InformationBox = ({title, imagePath, description}) => {
  return (
    <div>
      
    </div>
  )
}

export default InformationBox
```

- You can store image in `/src/components/assets` folder and then we can pass the path of this image to the `imagePath`

Relevant ScreenShot/Images

![image](https://github.com/user-attachments/assets/2e5724f9-1f09-449f-bac6-12521b87f423)

(Image referred above is at the center circle)

### References/Useful links:

- [https://www.freecodecamp.org/news/how-to-build-reusable-react-components/]()

**Comment by MedAzizGharbi** [comment]
Hi , can I work on this task ?

**Comment by Saumya40-codes** [comment]
> Hi , can I work on this task ?

Thanks but the contribution to this repository is only limited to inter-college event registered folks.

**Comment by vrunda2005** [comment]
Can I work on this component? One question: I have to create a component Informationbox, and to call it, do I have to create another file?

**Comment by Saumya40-codes** [comment]
> Can I work on this component? One question: I have to create a component Informationbox, and to call it, do I have to create another file?

No, for now we just need component, (we will call it iteratively three times as seen in the figma file, when we combine all/necessary Hero section components for this part)
