### ISSUE TITLE
Error while deploying development server

### ISSUE THREAD

**Issue by Kush-Kelaiya22** [Programming-Club-Ahmedabad-University/WOC-2024#18]
I just forked this repo and cloned it on my machine. As mentioned in the CONTRIBUTING.md, I tried to run the development server. However, I faced the following issue. I am new to JS, so i cannot understand it much.

`npm WARN lifecycle The node binary used for scripts is /snap/bin/node but npm is using /snap/node/4146/bin/node itself. Use the '--scripts-prepend-node-path' option to include the path for the node binary npm was executed with.

> woc2024@0.0.0 dev /home/kush/Codes/Open Source/WOC-2024
> vite

/home/kush/Codes/Open Source/WOC-2024/node_modules/vite/bin/vite.js:2
import { performance } from 'node:perf_hooks'
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! woc2024@0.0.0 dev: `vite`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the woc2024@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kush/.npm/_logs/2024-12-17T09_45_11_119Z-debug.log`

**Comment by Saumya40-codes** [comment]
> I just forked this repo and cloned it on my machine. As mentioned in the CONTRIBUTING.md, I tried to run the development server. However, I faced the following issue. I am new to JS, so i cannot understand it much.
> 
> `npm WARN lifecycle The node binary used for scripts is /snap/bin/node but npm is using /snap/node/4146/bin/node itself. Use the '--scripts-prepend-node-path' option to include the path for the node binary npm was executed with.
> 
> > woc2024@0.0.0 dev /home/kush/Codes/Open Source/WOC-2024
> > vite
> 
> /home/kush/Codes/Open Source/WOC-2024/node_modules/vite/bin/vite.js:2 import { performance } from 'node:perf_hooks' ^
> 
> SyntaxError: Unexpected token { at Module._compile (internal/modules/cjs/loader.js:723:23) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) at Function.Module.runMain (internal/modules/cjs/loader.js:831:12) at startup (internal/bootstrap/node.js:283:19) at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3) npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! woc2024@0.0.0 dev: `vite` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the woc2024@0.0.0 dev script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! /home/kush/.npm/_logs/2024-12-17T09_45_11_119Z-debug.log`

Hey there @Kush-Kelaiya22 !

There looks to be conflict between the binaries being used for node and npm

can you please try running this?

```
npm config set scripts-prepend-node-path auto
```

found similar issue like this on [here](https://stackoverflow.com/questions/51293566/how-to-include-the-path-for-the-node-binary-npm-was-executed-with)

If there is still problem, do tell !!

**Comment by Saumya40-codes** [comment]
@Kush-Kelaiya22 is this issue solved now?

**Comment by Kush-Kelaiya22** [comment]
> @Kush-Kelaiya22 is this issue solved now?

Unfortunately, it shows the same error after running the commands. I am still trying to figure out if there are missing packages or i have done something wrong with my setup. Thanks for the help.

**Comment by Kush-Kelaiya22** [comment]
I had a version issue with my node.js install. I update it to the latest version and had all the issues cleared.
