### ISSUE TITLE
[Component]: Build the Welcome Section Component (Hero Section 1/n)

### ISSUE THREAD

**Issue by Saumya40-codes** [Programming-Club-Ahmedabad-University/WOC-2024#2]
**Proposed Feature**

Create a Welcome Section component that displays:

- A heading: "Welcome !!"
- A sub-heading: "Programming Club - Ahmedabad University"
- A short description of the club.
- The text must be center-aligned and responsive for all screen sizes.

**Approach**

- Create a WelcomeSection component.

**Additional context**
- Please refer the **figma design** for this
- For now we are not focusing on responsiveness.
- You can use **lucide-react** for getting the preferred icons: [https://lucide.dev/icons/]()

**Relevant Images/ScreenShots**
![image](https://github.com/user-attachments/assets/5528852c-66f6-4d69-9b3e-8488757cdcf4)

**Comment by vishvboda** [comment]
Can you please assign this task gto me.

**Comment by Saumya40-codes** [comment]
> Can you please assign this task gto me.

👍 You can start working on it!

**Comment by vishvboda** [comment]
@Saumya40-codes in figma file text are left aligned, should I design component in left aligned or center aligned text?

**Comment by Saumya40-codes** [comment]
> @Saumya40-codes in figma file text are left aligned, should I design component in left aligned or center aligned text?

Yes, it should be left aligned, later it will be combined with the other components in the main page.
