### ISSUE TITLE
Setup Routes to redirect to new past events page

### ISSUE THREAD

**Issue by Saumya40-codes** [Programming-Club-Ahmedabad-University/WOC-2024#23]
### Description

In #20 there will be different section in navbar, one of which includes `Past Events`

When user clicks it, he should be redirected to `/past-events` page (i.e. `localhost:5173/past-events`)

### Possible Approach

- Use `BrowserRouter`, `Routes`, `Route` provided by `react-router-dom` package (this is already installed in the project) to define the routes.
- For now, we can make this directly in `src/App.jsx` folder
- If path = '/', then `HomePage` should be rendered.
- If path = `/past-events` then `PastEvents` page/component should be rendered
- `HomePage` and `PastEvents` doesnt exists for now so you can create them in `src/pages` folder (It's ok if they are an empty component for now)

**Additional context**

- https://www.w3schools.com/react/react_router.asp

**Comment by NareshPrabhu** [comment]
I've made changes as described above and submitted PR. Please check and confirm if any additional changes are needed

**Comment by kash2104** [comment]
@Saumya40-codes can I work on this issue?

**Comment by Saumya40-codes** [comment]
> @Saumya40-codes can I work on this issue?

👍 Assigned!

You can start with it.
