### ISSUE TITLE
[CI] Contributors logo in README.md doesn't update in real-time

### ISSUE THREAD

**Issue by Saumya40-codes** [Programming-Club-Ahmedabad-University/WOC-2024#26]
### Bug Details

In `README.md` file, we are using [https://contrib.rocks/preview?repo=Programming-Club-Ahmedabad-University%2FWOC-2024]() to get the logo of contributors in README.md. But turns out it doesnt happen in real-time and it might take days or weeks to be updated

Current state:
![image](https://github.com/user-attachments/assets/61b84bc4-3ff9-498c-b0e1-82442a96a03f)

Current contributors (last updated around 24 h. ago)
![image](https://github.com/user-attachments/assets/22721f7a-538c-418e-a55a-98add0de4cdd)

### Possible fix

Create a `github actions` workflow, so that when as pull request gets merged, the respective contributor's profile logo gets added into README.md (specific section), if it doesn't already exists

**Comment by vrunda2005** [comment]
Can I work on this issue?
