### ISSUE TITLE
[Design]: Develop the Upcoming Event Card Component

### ISSUE THREAD

**Issue by Saumya40-codes** [Programming-Club-Ahmedabad-University/WOC-2024#3]
**Proposed Feature**
Create a reusable card component to display details of upcoming events.

**Describe the solution you'd like**
- Create an EventCard component.
- Use props to pass event details (title, date, time).
- Style the component as per the figma design.

**Additional context**
- Note as a part of this issue you just have to create an **Event card component** i.e. the below component from figma design. Next we will reuse this same event card component for different event by passing there name, date, time, etc to this component.

![image](https://github.com/user-attachments/assets/0177e5e5-79a0-448d-8c3e-9f9d452f597b)

- Your react component might look like below 
   ```
    import React from 'react'
    
    const UpcomingEventCard= ({name, description, date, time, venue, teamsize}) => {
      return (
        <div>
          
        </div>
      )
    }

  export default UpcomingEventCard
   ```

- **Note**: For now, nothing needs to be happening when register is clicked

- You can use **lucide-react** for getting the preferred icons(if any): [https://lucide.dev/icons/]()

### References/Useful links:

- [https://www.freecodecamp.org/news/how-to-build-reusable-react-components/]()

**Comment by Fenil-1** [comment]
Can you assign it to me ?

**Comment by Saumya40-codes** [comment]
> Can you assign it to me ?

👍 You can start with this!

**Comment by Fenil-1** [comment]
Do i have to design the UpcomingEventCards max width as per figma design ?

**Comment by Saumya40-codes** [comment]
> Do i have to design the UpcomingEventCards max width as per figma design ?

Yes.
