### ISSUE TITLE
[Workflow] Create a Pull Request Template

### ISSUE THREAD

**Issue by Saumya40-codes** [Programming-Club-Ahmedabad-University/WOC-2024#5]
Add a standardized template for pull requests to ensure consistent and detailed submissions.

- When you submit a pull request, instead of empty input box, there will be pre existing content/template which can be filled, so that every pull request has a standardized description

### Approach:
- Create a `.github/PULL_REQUEST_TEMPLATE` folder and within that a `pull_request_template.md` file.

- An Ideal Pull Request should cover following at minimum
  - *Issue it is solving* (for e.g. solves/resolves/fixes #10 )     (Issue can be mentioned by `#` symbol follwed by issue number which can be seen just beside the issue title)\
  - Description of the changes made
  - A checkbox asking whether they've read CODE_OF_CONDUCT.md or not
  - A checkbox asking whether they've implemented design based on figma file only (if it contains one)

### Additional Context
- Note: There already exists a `.github/ISSUE_TEMPLATE` directory containing `bug_report.md` and `feature_request.md` templates for your reference.

**Comment by KushalXCoder** [comment]
Can I work on this ?

**Comment by Saumya40-codes** [comment]
> Can I work on this ?

Assingned to you!
