### ISSUE TITLE
[Component] Create a Responsive Footer

### ISSUE THREAD

**Issue by Saumya40-codes** [Programming-Club-Ahmedabad-University/WOC-2024#6]
Implement a footer with text, sitemap, company info, and social media icons.

### Approach:
- Create a Footer component.
- Use flex/grid for layout.
- Add hover effects for social media icons.

### Additional Context
- Refer to the Figma design: [https://www.figma.com/design/kHauIvxVeOb8diy8jO6jJd/Website?node-id=0-1&t=VaLTx4vGpSXga6dU-1]().
- You can use **lucide-react** for getting the preferred icons: [https://lucide.dev/icons/]()

**Relevant Images/ScreenShots**
![image](https://github.com/user-attachments/assets/2de171e8-702c-4a5c-9ac7-026cedfce95a)

**Comment by vrunda2005** [comment]
Can I work on this component?

**Comment by Saumya40-codes** [comment]
> Can I work on this component?

Yes, assigned to you!!
