### ISSUE TITLE
[Component] Social Media Icons Animation

### ISSUE THREAD

**Issue by Saumya40-codes** [Programming-Club-Ahmedabad-University/WOC-2024#7]
Create an interactive circular layout for social media icons.

### Approach:
- Use CSS animations or libraries like Framer Motion (checkout [here](https://motion.dev/) )
-  Add hover effects or tooltips for icons.
- Ensure accessibility.

## Additional Context
- Make this as a **component only**. Later this and **Contact Form** will be aligned together according to **Figma Design**
- Please refer to **Figma Designs only** for this.
- You can use any of the **chakra-ui** components for this: [https://v2.chakra-ui.com/docs/components]()
- You can use **lucide-react** for getting the preferred icons: [https://lucide.dev/icons/]()

## Relevant Images/ScreenShot

![image](https://github.com/user-attachments/assets/4391c607-13f8-42d4-bf6f-c3323628853f)

**Comment by vishvboda** [comment]
for this issue anyone can modify provided ui component as per figma design. It will be easy to implement this animation by this react component.

component link: https://magicui.design/docs/components/orbiting-circles

**Comment by Bansi-Mahkana** [comment]
I would like to work on this issue. Could you please assign it to me?

**Comment by Saumya40-codes** [comment]
> I would like to work on this issue. Could you please assign it to me?

Assigned to you!!
