### ISSUE TITLE
[Component]: Create a Contact Us Form Component

### ISSUE THREAD

**Issue by Saumya40-codes** [Programming-Club-Ahmedabad-University/WOC-2024#8]
#### Description
Develop a "Contact Us" form component where users can submit their inquiries. The form should include fields for name, email, and message, and provide appropriate error handling for invalid inputs.

**Form Now entries enter into this wont be sent/redirected anywhere, it will be part of seperate issue**

#### Approach
- Create a `ContactUsForm` component.
- Use controlled inputs to manage form state.
- Include fields:
  - **Name** (required, text input)
  - **Email** (required)
  - **Message** (required, textarea with a character limit).
- Implement basic form validation to ensure required fields are filled and inputs are valid.

### Additional Context
- Note create this as a component and not in main Home page file. Later this will be aligned with SocialMediaIcons component (ref issue #7 )
- Refer to the **Figma design** for layout and styling: [Figma Link](https://www.figma.com/design/kHauIvxVeOb8diy8jO6jJd/Website?node-id=0-1&t=VaLTx4vGpSXga6dU-1).

### Relevant Images/ScreenShots
![image](https://github.com/user-attachments/assets/6d70a75e-bd81-4b5e-b0db-afa17fb4c425)

**Comment by briang17** [comment]
@Saumya40-codes  hello! can I work on this?

**Comment by PrashamMehta-04** [comment]
Can I work on this component?

**Comment by Saumya40-codes** [comment]
> Can I work on this component?

👍 You can start with it!

**Comment by PrashamMehta-04** [comment]
![Screenshot 2024-12-21 102715](https://github.com/user-attachments/assets/2547c1f9-506b-4748-b075-62131ce63900)
As per the design in the figma (attached screenshot above), do I have to do the right side part because in the issues, right side part is not mentioned in it.

**Comment by Saumya40-codes** [comment]
> ![Screenshot 2024-12-21 102715](https://private-user-images.githubusercontent.com/133197683/397905532-2547c1f9-506b-4748-b075-62131ce63900.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NTc5ODUsIm5iZiI6MTczNDc1NzY4NSwicGF0aCI6Ii8xMzMxOTc2ODMvMzk3OTA1NTMyLTI1NDdjMWY5LTUwNmItNDc0OC1iMDc1LTYyMTMxY2U2MzkwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQwNTA4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDRkMGY1NmVhYmI1NjFlMmQxMDI3NTUwNWE4MmI1NDNkOTk4MWRkNzM4OTkyZjExNDNjMWMzMmI3ZWM1MjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2zHOpIBHfT4DgbTGuFnP8If9cFDkYZAryo3QS0rORbE) As per the design in the figma (attached screenshot above), do I have to do the right side part because in the issues, right side part is not mentioned in it.

Thats the part of another issue #7 . We will align both of them when their respective issue gets solved. But for the scope of this issue, you have to design the left side section (contact us form)

**Comment by PrashamMehta-04** [comment]
ohk, thanks!
