### ISSUE TITLE
[Component][Design]: Create an Our Events component

### ISSUE THREAD

**Issue by Saumya40-codes** [Programming-Club-Ahmedabad-University/WOC-2024#9]
Create an "Our Events" section as per the provided design, showcasing various events using cards, images, and typography.

**Approach**

1. **Header:**

- Implement a large "OUR EVENTS" text with layered effects.
  - Use proper font weights and sizes as seen in the design.

2. **Event Cards:**

- Each card contains an image, event name, and additional text/icons.
  - Layout the cards in a grid format for a clean, organized look.

3. **Styling:**

- Use CSS (or framer-motion) for animations, hover effects, and responsive design.
 - Fonts and colors should match the Figma design.
 - Add animations or transitions where needed for smooth visuals.
 

**Additional context**
- Refer to the **Figma design** for layout and styling: [Figma Link](https://www.figma.com/design/kHauIvxVeOb8diy8jO6jJd/Website?node-id=0-1&t=VaLTx4vGpSXga6dU-1).
- You can use **lucide-react** for getting the preferred icons: [https://lucide.dev/icons/]()

**Relevant Images/ScreenShots**
![image](https://github.com/user-attachments/assets/7564bbc1-b0f8-40a1-970b-3e07b3d31c3e)

**Comment by Daredevil124** [comment]
Please assign this to me

**Comment by Saumya40-codes** [comment]
> Please assign this to me

👍 You can start with it!

(maybe we wont be needing any UI component library(Chakra UI) for this) If there any issues we can discuss here or once you open the PR

**Comment by Daredevil124** [comment]
whats the last day to complete?

**Comment by Saumya40-codes** [comment]
> whats the last day to complete?

There is nothing like *time limit* but you can try not to take more than 2-3 (or max 4-5) days so that you can work on other things as well and others who might want to work on this can also get a fair chance(just in case if there are, otherwise it's ok). 
(If there's no one waiting, though, taking a bit longer is fine.)
